<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Npgsql.OpenTelemetry" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Enrichers.Environment" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        <PackageReference Include="MediatR" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Common\Domain.Common\Domain.Common.csproj" />
        <ProjectReference Include="..\RoiForm.Application\RoiForm.Application.csproj" />
        <ProjectReference Include="..\RoiForm.Domain\RoiForm.Domain.csproj" />
        <ProjectReference Include="..\RoiForm.Infrastructure\RoiForm.Infrastructure.csproj" />
    </ItemGroup>

</Project>
