// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoiForm.Infrastructure.Data;

#nullable disable

namespace RoiForm.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoiForm.Domain.FormManagement.Entities.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TemplateStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("roi_form_templates", (string)null);
                });

            modelBuilder.Entity("RoiForm.Domain.FormManagement.Entities.FormTemplate", b =>
                {
                    b.OwnsOne("RoiForm.Domain.FormManagement.ValueObjects.Formula", "Formula", b1 =>
                        {
                            b1.Property<Guid>("FormTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Expression")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("FormulaExpression");

                            b1.Property<string>("PostfixNotation")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("PostfixNotation");

                            b1.HasKey("FormTemplateId");

                            b1.ToTable("roi_form_templates");

                            b1.WithOwner()
                                .HasForeignKey("FormTemplateId");
                        });

                    b.OwnsMany("RoiForm.Domain.FormManagement.Entities.FormField", "FormFields", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("boolean");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<decimal?>("Max")
                                .HasColumnType("decimal(18,6)");

                            b1.Property<decimal?>("Min")
                                .HasColumnType("decimal(18,6)");

                            b1.Property<Guid>("RoiFormId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("RoiFormId");

                            b1.ToTable("roi_form_fields", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoiFormId");
                        });

                    b.Navigation("FormFields");

                    b.Navigation("Formula")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
